version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4

defaults:
  # This is a safe, basic set of configurations that jobs can default to.
  base: &base_defaults
    docker: 
      - image: circleci/node:latest #this should be set to a fixed version

dev-context: &dev-context
  context: dev
  filters:
    branches:
      only: develop

prod-context: &prod-context
  context: production
  filters:
    branches:
      only: master
  
jobs: 
  build-and-deploy:
    << : *base_defaults
    steps:
      - run: sudo apt-get update && sudo apt-get install -y python-pip libpython-dev
      - checkout
      - run: yarn && yarn export
      - aws-s3/copy:
          from: out/
          to: ${SNOWFLAKE_S3}
    
workflows:
  version: 2
  dev:
    jobs:
      - build-and-deploy:
          <<: *dev-context
  prod:
    jobs:
      - build-and-deploy:
          <<: *prod-context
